// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 2025/4/21 15:01:31
import configMerger from "@nuxtjs/tailwindcss/merger";

;
const config = [
{"content":{"files":["C:/Users/Lenovo/Desktop/trae-test/blog/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Lenovo/Desktop/trae-test/blog/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Lenovo/Desktop/trae-test/blog/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Lenovo/Desktop/trae-test/blog/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Lenovo/Desktop/trae-test/blog/plugins/**/*.{js,ts,mjs}","C:/Users/Lenovo/Desktop/trae-test/blog/composables/**/*.{js,ts,mjs}","C:/Users/Lenovo/Desktop/trae-test/blog/utils/**/*.{js,ts,mjs}","C:/Users/Lenovo/Desktop/trae-test/blog/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Lenovo/Desktop/trae-test/blog/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Lenovo/Desktop/trae-test/blog/app.config.{js,ts,mjs}"]}},
{}
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = (() => {const cfg=config;cfg["darkMode"] = ["selector","[class~=\"dark\"]"];;return cfg;})();

export default resolvedConfig;